// The three identity files jnaapakam treats as a persona's soul.
// Skeletons mirror jnaapakam 0.5.1's `jnaapakam init` templates
// (see cli.py SOUL_TEMPLATES in the yablokolabs/jnaapakam package) so that a
// downloaded set is byte-compatible with what `jnaapakam seal` expects to read.

export const SOUL_FILES = ["SOUL.md", "IDENTITY.md", "MEMORY.md"];

const SOUL_MD = `# SOUL.md

_Define who your agent is. This is loaded every session._

## Core Personality

<!-- How should your agent communicate? -->

## Boundaries

<!-- What should your agent never do? -->

## Preferences

<!-- Communication style preferences. -->
`;

const IDENTITY_MD = `# IDENTITY.md

- **Name:** <!-- Your agent's name -->
- **Emoji:** <!-- Signature emoji -->
- **Description:** <!-- One-line description -->
- **Created:** <!-- ISO date -->
`;

const MEMORY_MD = `# MEMORY.md

_Curated long-term memory. Organized by topic. Updated over time._

## User

## Projects

## Preferences

## Lessons Learned
`;

// A section's body can be a string or a list of strings. Lists become bullet
// points so that { boundaries: ["never X", "never Y"] } reads naturally.
function sectionBody(value) {
  if (value == null) return "";
  if (Array.isArray(value)) {
    const items = value.map((v) => String(v).trim()).filter(Boolean);
    return items.length ? items.map((v) => `- ${v}`).join("\n") : "";
  }
  return String(value).trim();
}

function replaceComment(block, comment, body) {
  return body ? block.replace(comment, body) : block;
}

export function renderSoul(p) {
  return replaceComment(
    replaceComment(
      replaceComment(
        SOUL_MD,
        "<!-- How should your agent communicate? -->",
        sectionBody(p.personality),
      ),
      "<!-- What should your agent never do? -->",
      sectionBody(p.boundaries),
    ),
    "<!-- Communication style preferences. -->",
    sectionBody(p.preferences),
  );
}

export function renderIdentity(p) {
  return IDENTITY_MD.replace("<!-- Your agent's name -->", p.name)
    .replace("<!-- Signature emoji -->", p.emoji || "")
    .replace("<!-- One-line description -->", p.description || "")
    .replace("<!-- ISO date -->", p.created);
}

export function renderMemory(p) {
  const mem = p.memory || {};
  const parts = [
    "# MEMORY.md",
    "",
    "_Curated long-term memory. Organized by topic. Updated over time._",
    "",
  ];
  const sections = [
    ["User", mem.user],
    ["Projects", mem.projects],
    ["Preferences", mem.preferences],
    ["Lessons Learned", mem.lessons],
  ];
  for (const [heading, value] of sections) {
    parts.push(`## ${heading}`, "");
    const body = sectionBody(value);
    if (body) parts.push(body, "");
  }
  return parts.join("\n").replace(/\n+$/, "\n");
}

// jnaapakam.yml — the same persona as one portable YAML manifest.
// Emitted deterministically (sorted keys) so identical personas hash alike.
export function renderYaml(p) {
  const lines = [];
  const push = (s) => lines.push(s);
  const scalar = (s) => {
    const str = String(s ?? "");
    if (str.includes("\n")) {
      return `|-\n${str
        .split("\n")
        .map((l) => `  ${l}`)
        .join("\n")}`;
    }
    return JSON.stringify(str);
  };
  const list = (arr) =>
    arr
      .map((v) => `  - ${v}`)
      .join("\n");

  push("# jnaapakam.yml");
  push("# Persona manifest for the jnaapakam memory protocol.");
  push("# Generated by the jnaapakam persona API; pair with SOUL.md, IDENTITY.md, MEMORY.md.");
  push("");
  push(`name: ${scalar(p.name)}`);
  if (p.emoji) push(`emoji: ${scalar(p.emoji)}`);
  if (p.description) push(`description: ${scalar(p.description)}`);
  push(`created: ${scalar(p.created)}`);
  push("soul:");
  const soulSection = (key, value) => {
    const body = sectionBody(value);
    if (body) push(`  ${key}: ${scalar(body)}`);
  };
  soulSection("core_personality", p.personality);
  if (p.boundaries && p.boundaries.length) {
    if (Array.isArray(p.boundaries)) {
      push(`  boundaries:\n${list(p.boundaries)}`);
    } else {
      soulSection("boundaries", p.boundaries);
    }
  }
  soulSection("preferences", p.preferences);
  const mem = p.memory || {};
  const memKeys = ["user", "projects", "preferences", "lessons"];
  if (memKeys.some((k) => sectionBody(mem[k]))) {
    push("memory:");
    for (const k of memKeys) {
      const body = sectionBody(mem[k]);
      if (body) push(`  ${k}: ${scalar(body)}`);
    }
  }
  return `${lines.join("\n")}\n`;
}
